### PR TITLE
Adapting to new PyAnsys actions v4 (main)

### PR DESCRIPTION
**Pull request by RobPasMue**
See https://dev.docs.pyansys.com/how-to/documenting.html#multi-version-migration-from-pyansys-actions-v3-to-pyansys-actions-v4

### CODE REVIEW

**Comment by greschd** [comment]
For this failure: maybe the location (or content?) of the `ansys-dpf-core` doc (for intersphinx) has changed?

**Comment by greschd** [comment]
> See https://dev.docs.pyansys.com/how-to/documenting.html#multi-version-migration-from-pyansys-actions-v3-to-pyansys-actions-v4

Thanks, I somehow missed the `conf.py` part.

**Review by greschd — APPROVED** [review]

**Comment by RobPasMue** [comment]
I'd stick to ``version/stable``. Thanks for looking into it @greschd!

**Comment by RobPasMue** [comment]
Feel free to merge whenever you want.

**Comment by greschd** [comment]
Thanks @RobPasMue!

**Comment by janvonrickenbach** [comment]
> For this failure: I think we need to update ` "ansys-dpf-core": ("https://dpf.docs.pyansys.com/release/0.7", None),` in the intersphinx mapping. Doc is now here: https://composites.dpf.docs.pyansys.com/version/stable/
> 
> @janvonrickenbach should we refer to the specific `ansys-dpf-core` version we are currently using, or just `stable`? The former means we have to manually update here, whereas the latter means it might be out of sync with what we use when `ansys-dpf-core` releases.

Using stable is find => I see you went with that solution.

**Pull request merged**
